# Generated by Django 4.0.10 on 2024-03-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='minimum_age',
            field=models.IntegerField(default=1, help_text="Baby's age in months"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
