# Generated by Django 4.0.10 on 2024-03-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/article/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/category/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/recipe/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/subcategory/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
